[package]
name = "ssh_trap"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
rand = "0.9"
rand_distr = "0.5"
tokio = { version = "1", features = ["full"] }
